/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_api_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/research-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Research Runs */
        get: operations["list_research_runs_api_research_runs_get"];
        put?: never;
        /** Create Research Runs */
        post: operations["create_research_runs_api_research_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/research-runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Research Run */
        get: operations["get_research_run_api_research_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/research-runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Research Run Events */
        get: operations["stream_research_run_events_api_research_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/research-runs/{run_id}/llm-calls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Research Run Llm Calls */
        get: operations["list_research_run_llm_calls_api_research_runs__run_id__llm_calls_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/research-runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Research Run */
        post: operations["cancel_research_run_api_research_runs__run_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/research-runs/{run_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume Research Run */
        post: operations["resume_research_run_api_research_runs__run_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/research-runs/{run_id}/macro-brief": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Macro Brief */
        get: operations["get_macro_brief_api_research_runs__run_id__macro_brief_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/screeners/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Screener */
        post: operations["run_screener_api_screeners_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/screeners/runs/{screener_run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Screener Run */
        get: operations["get_screener_run_api_screeners_runs__screener_run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/paper/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Paper Orders */
        get: operations["list_paper_orders_api_paper_orders_get"];
        put?: never;
        /** Create Paper Order */
        post: operations["create_paper_order_api_paper_orders_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/paper/portfolio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Paper Portfolio */
        get: operations["get_paper_portfolio_api_paper_portfolio_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data-health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Data Health Matrix */
        get: operations["get_data_health_matrix_api_data_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data-health/calls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Provider Calls */
        get: operations["list_provider_calls_api_data_health_calls_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Provider Settings */
        get: operations["get_provider_settings_api_settings_providers_get"];
        /** Update Provider Settings */
        put: operations["update_provider_settings_api_settings_providers_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/watchlists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Watchlists */
        get: operations["list_watchlists_api_watchlists_get"];
        put?: never;
        /** Create Watchlist */
        post: operations["create_watchlist_api_watchlists_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/watchlists/{watchlist_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Watchlist */
        get: operations["get_watchlist_api_watchlists__watchlist_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/watchlists/{watchlist_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Watchlist Member */
        post: operations["add_watchlist_member_api_watchlists__watchlist_id__members_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/watchlists/{watchlist_id}/members/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Watchlist Member */
        delete: operations["remove_watchlist_member_api_watchlists__watchlist_id__members__ticker__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AnalystKindEnum
         * @enum {string}
         */
        AnalystKindEnum: "bull" | "bear" | "macro" | "fundamentals" | "sentiment" | "risk";
        /** ApplicationSettingsPublic */
        ApplicationSettingsPublic: {
            /** Id */
            id: number;
            llm_provider: components["schemas"]["LlmProviderEnum"];
            /** Llm Model */
            llm_model: string;
            /** Default Analyst Set */
            default_analyst_set: string[];
            /** Default Depth */
            default_depth: number;
            /** Default Model */
            default_model: string;
            /** Llm Api Key Masked */
            llm_api_key_masked?: string | null;
            /** Alpha Vantage Key Masked */
            alpha_vantage_key_masked?: string | null;
            /**
             * Has Llm Api Key
             * @default false
             */
            has_llm_api_key: boolean;
            /**
             * Has Alpha Vantage Key
             * @default false
             */
            has_alpha_vantage_key: boolean;
        };
        /** ChunkLookup */
        ChunkLookup: {
            /**
             * Chunk Id
             * Format: uuid
             */
            chunk_id: string;
            /**
             * Evidence Id
             * Format: uuid
             */
            evidence_id: string;
            /** Source */
            source: string;
            /** Text */
            text: string;
            /** Attributes */
            attributes: {
                [key: string]: unknown;
            };
        };
        /** CitedClaim */
        CitedClaim: {
            /** Claim Text */
            claim_text: string;
            /** Exact Quote */
            exact_quote: string;
            /**
             * Chunk Id
             * Format: uuid
             */
            chunk_id: string;
            /** Source */
            source: string;
        };
        /** CreatePaperOrderRequest */
        CreatePaperOrderRequest: {
            /**
             * Portfolio Id
             * Format: uuid
             */
            portfolio_id: string;
            /** Ticker */
            ticker: string;
            side: components["schemas"]["OrderSideEnum"];
            /** Quantity */
            quantity: number;
            /** @default market */
            order_type: components["schemas"]["OrderTypeEnum"];
            /** Source Run Id */
            source_run_id?: string | null;
        };
        /** CreateResearchRunsRequest */
        CreateResearchRunsRequest: {
            /** @default tradingagents */
            strategy: components["schemas"]["StrategyEnum"];
            /**
             * Trade Date
             * Format: date
             */
            trade_date: string;
            /** Tickers */
            tickers?: string[] | null;
            scope_payload?: components["schemas"]["MacroBriefScope"] | null;
            /** Analysts */
            analysts?: components["schemas"]["AnalystKindEnum"][];
            llm_provider?: components["schemas"]["LlmProviderEnum"] | null;
            /** Llm Model */
            llm_model?: string | null;
            /**
             * Debate Depth
             * @default 3
             */
            debate_depth: number;
        };
        /**
         * FinalRatingEnum
         * @enum {string}
         */
        FinalRatingEnum: "buy" | "hold" | "sell" | "none";
        /** GroupedRuns */
        GroupedRuns: {
            /** Queued */
            queued: components["schemas"]["ResearchRunSummary"][];
            /** Running */
            running: components["schemas"]["ResearchRunSummary"][];
            /** Recent */
            recent: components["schemas"]["ResearchRunSummary"][];
            /** Failed */
            failed: components["schemas"]["ResearchRunSummary"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            /** Version */
            version: string;
        };
        /** LlmCallLogPublic */
        LlmCallLogPublic: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Run Id */
            run_id: string | null;
            /** Model */
            model: string;
            /** Prompt Hash */
            prompt_hash: string;
            /** Input Hash */
            input_hash: string;
            /** Input Tokens */
            input_tokens: number;
            /** Output Tokens */
            output_tokens: number;
            /** Cached Input Tokens */
            cached_input_tokens: number;
            /** Reasoning Tokens */
            reasoning_tokens: number;
            /** Cost Usd */
            cost_usd: string;
            /** Latency Ms */
            latency_ms: number;
            status: components["schemas"]["LlmCallStatusEnum"];
            /** Error Message */
            error_message: string | null;
            /** Evidence Ids */
            evidence_ids: string[] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * LlmCallStatusEnum
         * @enum {string}
         */
        LlmCallStatusEnum: "success" | "error" | "budget_paused" | "budget_killed";
        /**
         * LlmProviderEnum
         * @enum {string}
         */
        LlmProviderEnum: "openai" | "anthropic" | "together";
        /** MacroBrief */
        MacroBrief: {
            /** Themes */
            themes: components["schemas"]["Theme"][];
            /** Sector Calls */
            sector_calls: components["schemas"]["SectorCall"][];
            /** Watch Items */
            watch_items: components["schemas"]["WatchItem"][];
            /** Cited Claims */
            cited_claims: components["schemas"]["CitedClaim"][];
            /** Proposed Hypotheses */
            proposed_hypotheses: components["schemas"]["ProposedHypothesis"][];
            /** Confidence */
            confidence: number;
            /** Evidence Ids */
            evidence_ids: string[];
            verifier_status: components["schemas"]["VerifierStatus"];
            /** Regeneration Count */
            regeneration_count: number;
        };
        /** MacroBriefPublic */
        MacroBriefPublic: {
            brief: components["schemas"]["MacroBrief"];
            /** Chunks */
            chunks: components["schemas"]["ChunkLookup"][];
        };
        /** MacroBriefScope */
        MacroBriefScope: {
            /**
             * Kind
             * @constant
             */
            kind: "macro";
            /**
             * Universe
             * @constant
             */
            universe: "us_equities";
        };
        /** NotReadyResponse */
        NotReadyResponse: {
            /**
             * Status
             * @constant
             */
            status: "not_ready";
            /** Reason */
            reason: string;
        };
        /**
         * OrderSideEnum
         * @enum {string}
         */
        OrderSideEnum: "buy" | "sell";
        /**
         * OrderStatusEnum
         * @enum {string}
         */
        OrderStatusEnum: "pending" | "accepted" | "filled" | "cancelled" | "rejected";
        /**
         * OrderTypeEnum
         * @enum {string}
         */
        OrderTypeEnum: "market";
        /** PaperOrderPublic */
        PaperOrderPublic: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Portfolio Id
             * Format: uuid
             */
            portfolio_id: string;
            /** Ticker */
            ticker: string;
            side: components["schemas"]["OrderSideEnum"];
            /** Quantity */
            quantity: number;
            order_type: components["schemas"]["OrderTypeEnum"];
            status: components["schemas"]["OrderStatusEnum"];
            /**
             * Submitted At
             * Format: date-time
             */
            submitted_at: string;
            /** Filled At */
            filled_at: string | null;
            /** Filled Price Cents */
            filled_price_cents: number | null;
            /** Source Run Id */
            source_run_id: string | null;
        };
        /** PaperPortfolioSnapshot */
        PaperPortfolioSnapshot: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Cash Cents */
            cash_cents: number;
            /** Equity Cents */
            equity_cents: number;
            /** Unrealized Pl Cents */
            unrealized_pl_cents: number;
            /** Realized Pl Cents */
            realized_pl_cents: number;
            /** Positions */
            positions: components["schemas"]["PaperPositionPublic"][];
        };
        /** PaperPositionPublic */
        PaperPositionPublic: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Portfolio Id
             * Format: uuid
             */
            portfolio_id: string;
            /** Ticker */
            ticker: string;
            /** Quantity */
            quantity: number;
            /** Avg Cost Cents */
            avg_cost_cents: number;
            /** Mark Cents */
            mark_cents: number;
            /**
             * Opened At
             * Format: date-time
             */
            opened_at: string;
            /** Closed At */
            closed_at: string | null;
        };
        /** ProposedHypothesis */
        ProposedHypothesis: {
            /** Claim Text */
            claim_text: string;
            /** Scope Entity Ids */
            scope_entity_ids: string[];
            /** Evidence Ids */
            evidence_ids: string[];
        };
        /**
         * ProvenanceStatusEnum
         * @enum {string}
         */
        ProvenanceStatusEnum: "success" | "failure" | "partial";
        /** ProviderCheckPublic */
        ProviderCheckPublic: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Provider */
            provider: string;
            /** Tool */
            tool: string;
            /** Ticker */
            ticker: string | null;
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** Latency Ms */
            latency_ms: number;
            status: components["schemas"]["ProviderCheckStatusEnum"];
            /** Sample Count */
            sample_count: number;
            /** As Of */
            as_of: string | null;
            /** Error Message */
            error_message: string | null;
        };
        /**
         * ProviderCheckStatusEnum
         * @enum {string}
         */
        ProviderCheckStatusEnum: "success" | "failure" | "partial";
        /** ProviderMatrix */
        ProviderMatrix: {
            /** Providers */
            providers: string[];
            /** Tools */
            tools: string[];
            /** Cells */
            cells: components["schemas"]["ProviderMatrixCell"][];
        };
        /** ProviderMatrixCell */
        ProviderMatrixCell: {
            /** Provider */
            provider: string;
            /** Tool */
            tool: string;
            status: components["schemas"]["ProviderCheckStatusEnum"];
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** Latency Ms */
            latency_ms: number;
            /** Sample Count */
            sample_count: number;
            /** As Of */
            as_of: string | null;
        };
        /** ReadyResponse */
        ReadyResponse: {
            /**
             * Status
             * @constant
             */
            status: "ready";
        };
        /** ResearchRunDetail */
        ResearchRunDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Ticker */
            ticker: string | null;
            /**
             * Trade Date
             * Format: date
             */
            trade_date: string;
            strategy: components["schemas"]["StrategyEnum"];
            status: components["schemas"]["RunStatusEnum"];
            /** Config */
            config: {
                [key: string]: unknown;
            };
            final_rating: components["schemas"]["FinalRatingEnum"] | null;
            /** Final Decision Summary */
            final_decision_summary: string | null;
            /** Wall Clock Ms */
            wall_clock_ms: number | null;
            /** Error Message */
            error_message: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Reports */
            reports: components["schemas"]["RunReportPublic"][];
            /** Events */
            events: components["schemas"]["RunEventPublic"][];
            /** Provenance */
            provenance: components["schemas"]["SourceProvenancePublic"][];
        };
        /** ResearchRunSummary */
        ResearchRunSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Ticker */
            ticker: string | null;
            strategy: components["schemas"]["StrategyEnum"];
            status: components["schemas"]["RunStatusEnum"];
            final_rating: components["schemas"]["FinalRatingEnum"] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Queue Position */
            queue_position?: number | null;
        };
        /**
         * RunEventLevelEnum
         * @enum {string}
         */
        RunEventLevelEnum: "info" | "warn" | "err";
        /** RunEventPublic */
        RunEventPublic: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * At
             * Format: date-time
             */
            at: string;
            level: components["schemas"]["RunEventLevelEnum"];
            /** Message */
            message: string;
            /** Data */
            data: {
                [key: string]: unknown;
            } | null;
        };
        /** RunReportPublic */
        RunReportPublic: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            analyst: components["schemas"]["AnalystKindEnum"];
            /** Markdown */
            markdown: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * RunStatusEnum
         * @enum {string}
         */
        RunStatusEnum: "queued" | "running" | "succeeded" | "failed" | "cancelled" | "paused";
        /** ScreenerResultPublic */
        ScreenerResultPublic: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Screener Run Id
             * Format: uuid
             */
            screener_run_id: string;
            /** Ticker */
            ticker: string;
            /** Score */
            score: number;
            /** Factor Scores */
            factor_scores: {
                [key: string]: number;
            };
        };
        /** ScreenerRunPublic */
        ScreenerRunPublic: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Universe */
            universe: string;
            /** Factor Weights */
            factor_weights: {
                [key: string]: number;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Finished At */
            finished_at: string | null;
            /** Result Count */
            result_count: number | null;
        };
        /** ScreenerRunRequest */
        ScreenerRunRequest: {
            universe: components["schemas"]["ScreenerUniverseEnum"];
            /** Watchlist Id */
            watchlist_id?: string | null;
            /** Factor Weights */
            factor_weights?: {
                [key: string]: number;
            };
            /**
             * Limit
             * @default 50
             */
            limit: number;
        };
        /** ScreenerRunResponse */
        ScreenerRunResponse: {
            screener_run: components["schemas"]["ScreenerRunPublic"];
            /** Results */
            results: components["schemas"]["ScreenerResultPublic"][];
        };
        /**
         * ScreenerUniverseEnum
         * @enum {string}
         */
        ScreenerUniverseEnum: "sp500" | "nasdaq100" | "watchlist";
        /** SectorCall */
        SectorCall: {
            /**
             * Sector Entity Id
             * Format: uuid
             */
            sector_entity_id: string;
            /** Sector Name */
            sector_name: string;
            direction: components["schemas"]["SectorCallDirection"];
            /** Conviction */
            conviction: number;
            /** Evidence Ids */
            evidence_ids: string[];
        };
        /**
         * SectorCallDirection
         * @enum {string}
         */
        SectorCallDirection: "overweight" | "underweight" | "neutral";
        /** SourceProvenancePublic */
        SourceProvenancePublic: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Provider */
            provider: string;
            /** Tool */
            tool: string;
            /** Ticker */
            ticker: string;
            /**
             * Request At
             * Format: date-time
             */
            request_at: string;
            /** Latency Ms */
            latency_ms: number;
            status: components["schemas"]["ProvenanceStatusEnum"];
            /** Sample Count */
            sample_count: number;
            /** As Of */
            as_of: string | null;
            /** Error Message */
            error_message: string | null;
        };
        /**
         * StrategyEnum
         * @enum {string}
         */
        StrategyEnum: "tradingagents" | "funnel_research";
        /** Theme */
        Theme: {
            /** Name */
            name: string;
            /** Evidence Ids */
            evidence_ids: string[];
            /** Confidence */
            confidence: number;
        };
        /** UpdateApplicationSettingsRequest */
        UpdateApplicationSettingsRequest: {
            llm_provider?: components["schemas"]["LlmProviderEnum"] | null;
            /** Llm Model */
            llm_model?: string | null;
            /** Llm Api Key */
            llm_api_key?: string | null;
            /** Alpha Vantage Key */
            alpha_vantage_key?: string | null;
            /** Default Analyst Set */
            default_analyst_set?: string[] | null;
            /** Default Depth */
            default_depth?: number | null;
            /** Default Model */
            default_model?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * VerifierStatus
         * @enum {string}
         */
        VerifierStatus: "verified" | "quote_unverified";
        /** WatchItem */
        WatchItem: {
            /** Name */
            name: string;
            /** Reason */
            reason: string;
            /** Evidence Ids */
            evidence_ids: string[];
        };
        /** WatchlistCreate */
        WatchlistCreate: {
            /** Name */
            name: string;
        };
        /** WatchlistDetail */
        WatchlistDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Members */
            members: components["schemas"]["WatchlistMemberPublic"][];
        };
        /** WatchlistMemberAdd */
        WatchlistMemberAdd: {
            /** Ticker */
            ticker: string;
            /** Notes */
            notes?: string | null;
        };
        /** WatchlistMemberPublic */
        WatchlistMemberPublic: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Watchlist Id
             * Format: uuid
             */
            watchlist_id: string;
            /** Ticker */
            ticker: string;
            /** Notes */
            notes: string | null;
            /**
             * Added At
             * Format: date-time
             */
            added_at: string;
        };
        /** WatchlistPublic */
        WatchlistPublic: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    ready_api_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotReadyResponse"];
                };
            };
        };
    };
    list_research_runs_api_research_runs_get: {
        parameters: {
            query?: {
                status?: string[] | null;
                ticker?: string | null;
                limit?: number;
                offset?: number;
                group?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchRunSummary"][] | components["schemas"]["GroupedRuns"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_research_runs_api_research_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateResearchRunsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchRunSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_research_run_api_research_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchRunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_research_run_events_api_research_runs__run_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_research_run_llm_calls_api_research_runs__run_id__llm_calls_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LlmCallLogPublic"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_research_run_api_research_runs__run_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchRunSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_research_run_api_research_runs__run_id__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchRunSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_macro_brief_api_research_runs__run_id__macro_brief_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MacroBriefPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_screener_api_screeners_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScreenerRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScreenerRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_screener_run_api_screeners_runs__screener_run_id__get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                screener_run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScreenerRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_paper_orders_api_paper_orders_get: {
        parameters: {
            query: {
                portfolio_id: string;
                status?: components["schemas"]["OrderStatusEnum"] | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaperOrderPublic"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_paper_order_api_paper_orders_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePaperOrderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaperOrderPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_paper_portfolio_api_paper_portfolio_get: {
        parameters: {
            query?: {
                portfolio_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaperPortfolioSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_data_health_matrix_api_data_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderMatrix"];
                };
            };
        };
    };
    list_provider_calls_api_data_health_calls_get: {
        parameters: {
            query: {
                provider: string;
                tool: string;
                ticker?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderCheckPublic"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_provider_settings_api_settings_providers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationSettingsPublic"];
                };
            };
        };
    };
    update_provider_settings_api_settings_providers_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateApplicationSettingsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationSettingsPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_watchlists_api_watchlists_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistPublic"][];
                };
            };
        };
    };
    create_watchlist_api_watchlists_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchlistCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_watchlist_api_watchlists__watchlist_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                watchlist_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_watchlist_member_api_watchlists__watchlist_id__members_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                watchlist_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchlistMemberAdd"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistMemberPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_watchlist_member_api_watchlists__watchlist_id__members__ticker__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                watchlist_id: string;
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
